### ISSUE TITLE
Gulp 4?

### ISSUE THREAD

**Issue by grauschnabel** [edouardl/bt-sass-blank-theme#1]
Hi there,

I the this error on running gulp:
```
assert.js:247
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/martin/Projects/docker/wordpress/barfuss-eins/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/martin/Projects/docker/wordpress/barfuss-eins/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/martin/Projects/docker/wordpress/barfuss-eins/gulpfile.js:42:6)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```
According to [](https://stackoverflow.com/questions/38182410/gulp-error-in-console-assert-js90-throw-new-assert-assertionerror) this could be a problem with the gulp version.  I have here
```
[20:17:42] CLI version 2.0.0
[20:17:42] Local version 4.0.0
```

So please could you update this for me?  I'm just learning gulp.

**Comment by edouardl** [comment]
Hello,
The theme seems to not be compatible with gulp 4 right now. I'm working on it.
I advice you to use gulp 3.9.1 locally for your project with this theme until I finish the compatibility fixes.

Regards
Edouard

**Comment by edouardl** [comment]
Hello,
The theme works with gulp v4.0.0
Regards,
Edouard
